
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Resolve a `convo://` URL and load the referenced conversation.
 */
async loadConversation(url: string) : Promise<Result<LoadedConversation, ConvoError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_conversation", { url }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The deep-link URL the app was cold-started with, if any. Read by the frontend
 * on load instead of the plugin's stricter `getCurrent()`.
 */
async initialUrl() : Promise<string | null> {
    return await TAURI_INVOKE("initial_url");
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * User `message.content` is either a plain prompt string or an array of blocks.
 */
export type Content = string | ContentBlock[]
/**
 * A content block. Unknown block kinds are preserved as raw JSON so they can be
 * rendered as a visible "unrecognized" node instead of being dropped.
 */
export type ContentBlock = KnownBlock | JsonValue
/**
 * One line of a conversation `.jsonl`, decoded leniently.
 * 
 * Mirrors the Claude Code wire format directly (v1 is intentionally coupled to
 * it). Every non-guaranteed field is optional so unknown shapes never fail to
 * decode. `parse_error` is synthesized by the parser for lines that fail to
 * decode as JSON; it is never present in the source.
 */
export type ConversationEvent = { type?: string; uuid?: string | null; parentUuid?: string | null; timestamp?: string | null; sessionId?: string | null; cwd?: string | null; gitBranch?: string | null; message?: Message | null; subtype?: string | null; level?: string | null; content?: JsonValue | null; attachment?: JsonValue | null; prUrl?: string | null; prRepository?: string | null; prNumber?: number | null; toolUseResult?: JsonValue | null; 
/**
 * Set by the parser when the raw line could not be decoded as JSON.
 * Never present in source `.jsonl`; synthesized by the parser only.
 */
parseError?: ParseError | null }
/**
 * Error returned across the Tauri boundary. Serializes to a tagged object the
 * frontend can switch on.
 */
export type ConvoError = { kind: "InvalidUrl"; message: string } | { kind: "PathTraversal"; message: string } | { kind: "NotFound"; message: string } | { kind: "Io"; message: string } | { kind: "NoHome" }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type KnownBlock = { type: "text"; text: string } | { type: "thinking"; thinking: string } | { type: "tool_use"; id: string; name: string; input: JsonValue } | { type: "tool_result"; tool_use_id: string; content: ToolResultContent; is_error?: boolean }
/**
 * The payload returned to the frontend: the ordered events plus the optional
 * turn anchor parsed from the URL fragment.
 */
export type LoadedConversation = { events: ConversationEvent[]; anchor: string | null }
export type Message = { role?: string | null; content: Content }
export type ParseError = { line_number: number; raw: string; message: string }
export type ToolResultContent = string | JsonValue[]

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
