
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Resolve a `convo://` URL and load the referenced conversation.
 */
async loadConversation(url: string) : Promise<Result<LoadedConversation, ConvoError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_conversation", { url }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The deep-link URL the app was cold-started with, if any. Read by the frontend
 * on load instead of the plugin's stricter `getCurrent()`.
 */
async initialUrl() : Promise<string | null> {
    return await TAURI_INVOKE("initial_url");
},
/**
 * Prompt for a destination with a native save dialog and write `html` there.
 * 
 * The frontend builds a self-contained HTML document (rendered transcript +
 * inlined styles); this just handles the picker and the file write. Returns the
 * saved path, or `None` if the user cancelled.
 */
async exportHtml(defaultName: string, html: string) : Promise<Result<string | null, ConvoError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_html", { defaultName, html }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * One block within an assistant turn.
 */
export type AssistantBlock = 
/**
 * Assistant prose, rendered as markdown.
 */
{ kind: "markdown"; text: string } | 
/**
 * Extended thinking. Only emitted when non-empty.
 */
{ kind: "thinking"; text: string } | 
/**
 * A tool invocation with its result joined in (None if not yet available).
 */
{ kind: "toolCall"; id: string; name: string; input: JsonValue; result: ToolResult | null } | 
/**
 * An unrecognized content block, preserved as raw JSON.
 */
{ kind: "unknown"; raw: JsonValue }
/**
 * Computed statistics for a whole conversation, shown in the collapsed
 * "Conversation details" item at the end of the transcript.
 */
export type ConversationStats = { 
/**
 * User + assistant message events (the "turns" headline count).
 */
turns: number; userTurns: number; assistantTurns: number; 
/**
 * Tool invocations grouped by tool name, descending by count.
 */
toolCalls: NamedCount[]; totalToolCalls: number; failedToolCalls: number; tokens: TokenTotals; 
/**
 * cache_read / (cache_read + cache_creation + input), or None if no input.
 */
cacheHitRate: number | null; 
/**
 * Distinct models seen (excluding the `<synthetic>` placeholder).
 */
models: string[]; cwd: string | null; gitBranch: string | null; version: string | null }
/**
 * Error returned across the Tauri boundary. Serializes to a tagged object the
 * frontend can switch on.
 */
export type ConvoError = { kind: "InvalidUrl"; message: string } | { kind: "PathTraversal"; message: string } | { kind: "NotFound"; message: string } | { kind: "Io"; message: string } | { kind: "NoHome" }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
/**
 * The payload returned to the frontend: the structured render model, the
 * optional turn anchor parsed from the URL fragment, and aggregate stats for
 * the conversation-details summary.
 */
export type LoadedConversation = { items: RenderItem[]; anchor: string | null; stats: ConversationStats }
/**
 * A `(name, count)` pair, e.g. how many times a given tool was called.
 */
export type NamedCount = { name: string; count: number }
/**
 * A top-level item in the rendered transcript, paired with whether it is part
 * of the normally-hidden noise (attachments, stop-hook summaries, queue ops,
 * filler turns). The frontend hides these unless "Show hidden" is on.
 */
export type RenderItem = (
/**
 * A genuine human prompt (string content, or array content containing text).
 */
{ kind: "userPrompt"; uuid: string | null; text: string } | 
/**
 * A system-injected "user" turn (e.g. `<task-notification>`, slash-command
 * invocations, continuation prompts) — not something the human typed.
 * Rendered collapsed, showing `summary` when available.
 */
{ kind: "notice"; uuid: string | null; text: string; summary: string | null } | 
/**
 * An assistant turn with its inline blocks (text, thinking, tool calls).
 */
{ kind: "assistantTurn"; uuid: string | null; blocks: AssistantBlock[] } | { kind: "system"; uuid: string | null; subtype: string | null; content: JsonValue | null } | { kind: "attachment"; uuid: string | null; content: JsonValue | null } | { kind: "prLink"; uuid: string | null; url: string | null; number: number | null } | 
/**
 * An unrecognized event type, preserved as raw JSON.
 */
{ kind: "unknown"; uuid: string | null; label: string; raw: JsonValue } | { kind: "parseError"; uuid: string | null; lineNumber: number; raw: string }) & { hidden: boolean }
/**
 * Aggregate token usage across all assistant turns.
 */
export type TokenTotals = { input: number; output: number; cacheCreation: number; cacheRead: number }
/**
 * A tool call's result, joined from the `tool_result` block that appears in a
 * later user turn.
 */
export type ToolResult = { content: JsonValue; isError: boolean }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
